SOURCES += \
    ../../jni/ImageMagick/MagickCore/accelerate.c \
    ../../jni/ImageMagick/MagickCore/animate.c \
    ../../jni/ImageMagick/MagickCore/annotate.c \
    ../../jni/ImageMagick/MagickCore/artifact.c \
    ../../jni/ImageMagick/MagickCore/attribute.c \
    ../../jni/ImageMagick/MagickCore/blob.c \
    ../../jni/ImageMagick/MagickCore/cache.c \
    ../../jni/ImageMagick/MagickCore/cache-view.c \
    ../../jni/ImageMagick/MagickCore/channel.c \
    ../../jni/ImageMagick/MagickCore/cipher.c \
    ../../jni/ImageMagick/MagickCore/client.c \
    ../../jni/ImageMagick/MagickCore/coder.c \
    ../../jni/ImageMagick/MagickCore/color.c \
    ../../jni/ImageMagick/MagickCore/colormap.c \
    ../../jni/ImageMagick/MagickCore/colorspace.c \
    ../../jni/ImageMagick/MagickCore/compare.c \
    ../../jni/ImageMagick/MagickCore/composite.c \
    ../../jni/ImageMagick/MagickCore/compress.c \
    ../../jni/ImageMagick/MagickCore/configure.c \
    ../../jni/ImageMagick/MagickCore/constitute.c \
    ../../jni/ImageMagick/MagickCore/decorate.c \
    ../../jni/ImageMagick/MagickCore/delegate.c \
    ../../jni/ImageMagick/MagickCore/deprecate.c \
    ../../jni/ImageMagick/MagickCore/display.c \
    ../../jni/ImageMagick/MagickCore/distort.c \
    ../../jni/ImageMagick/MagickCore/distribute-cache.c \
    ../../jni/ImageMagick/MagickCore/draw.c \
    ../../jni/ImageMagick/MagickCore/effect.c \
    ../../jni/ImageMagick/MagickCore/enhance.c \
    ../../jni/ImageMagick/MagickCore/exception.c \
    ../../jni/ImageMagick/MagickCore/feature.c \
    ../../jni/ImageMagick/MagickCore/fourier.c \
    ../../jni/ImageMagick/MagickCore/fx.c \
    ../../jni/ImageMagick/MagickCore/gem.c \
    ../../jni/ImageMagick/MagickCore/geometry.c \
    ../../jni/ImageMagick/MagickCore/histogram.c \
    ../../jni/ImageMagick/MagickCore/identify.c \
    ../../jni/ImageMagick/MagickCore/image.c \
    ../../jni/ImageMagick/MagickCore/image-view.c \
    ../../jni/ImageMagick/MagickCore/layer.c \
    ../../jni/ImageMagick/MagickCore/linked-list.c \
    ../../jni/ImageMagick/MagickCore/list.c \
    ../../jni/ImageMagick/MagickCore/locale.c \
    ../../jni/ImageMagick/MagickCore/log.c \
    ../../jni/ImageMagick/MagickCore/magic.c \
    ../../jni/ImageMagick/MagickCore/magick.c \
    ../../jni/ImageMagick/MagickCore/matrix.c \
    ../../jni/ImageMagick/MagickCore/memory.c \
    ../../jni/ImageMagick/MagickCore/mime.c \
    ../../jni/ImageMagick/MagickCore/module.c \
    ../../jni/ImageMagick/MagickCore/monitor.c \
    ../../jni/ImageMagick/MagickCore/montage.c \
    ../../jni/ImageMagick/MagickCore/morphology.c \
    ../../jni/ImageMagick/MagickCore/nt-base.c \
    ../../jni/ImageMagick/MagickCore/nt-feature.c \
    ../../jni/ImageMagick/MagickCore/opencl.c \
    ../../jni/ImageMagick/MagickCore/option.c \
    ../../jni/ImageMagick/MagickCore/paint.c \
    ../../jni/ImageMagick/MagickCore/pixel.c \
    ../../jni/ImageMagick/MagickCore/policy.c \
    ../../jni/ImageMagick/MagickCore/prepress.c \
    ../../jni/ImageMagick/MagickCore/profile.c \
    ../../jni/ImageMagick/MagickCore/property.c \
    ../../jni/ImageMagick/MagickCore/quantize.c \
    ../../jni/ImageMagick/MagickCore/quantum.c \
    ../../jni/ImageMagick/MagickCore/quantum-export.c \
    ../../jni/ImageMagick/MagickCore/quantum-import.c \
    ../../jni/ImageMagick/MagickCore/random.c \
    ../../jni/ImageMagick/MagickCore/registry.c \
    ../../jni/ImageMagick/MagickCore/resample.c \
    ../../jni/ImageMagick/MagickCore/resize.c \
    ../../jni/ImageMagick/MagickCore/resource.c \
    ../../jni/ImageMagick/MagickCore/segment.c \
    ../../jni/ImageMagick/MagickCore/semaphore.c \
    ../../jni/ImageMagick/MagickCore/shear.c \
    ../../jni/ImageMagick/MagickCore/signature.c \
    ../../jni/ImageMagick/MagickCore/splay-tree.c \
    ../../jni/ImageMagick/MagickCore/static.c \
    ../../jni/ImageMagick/MagickCore/statistic.c \
    ../../jni/ImageMagick/MagickCore/stream.c \
    ../../jni/ImageMagick/MagickCore/string.c \
    ../../jni/ImageMagick/MagickCore/thread.c \
    ../../jni/ImageMagick/MagickCore/threshold.c \
    ../../jni/ImageMagick/MagickCore/timer.c \
    ../../jni/ImageMagick/MagickCore/token.c \
    ../../jni/ImageMagick/MagickCore/transform.c \
    ../../jni/ImageMagick/MagickCore/type.c \
    ../../jni/ImageMagick/MagickCore/utility.c \
    ../../jni/ImageMagick/MagickCore/version.c \
    ../../jni/ImageMagick/MagickCore/vision.c \
    ../../jni/ImageMagick/MagickCore/widget.c \
    ../../jni/ImageMagick/MagickCore/xml-tree.c \
    ../../jni/ImageMagick/MagickCore/xwindow.c \
